# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c960d7019461f1658d67c5f1835158b1673d662d9234e9c7d2d929e024cae4396ed7f04b1fb68348e73d21680d27ad1a90c284688d33d53c56039c9293ed05d

test:
  secret_key_base: 425ddc9a36076e549669c7fba53f9369cbc0ba670d936dbcd584cf3fecf392a96685a8f0a1cc2dd3abe6019f5ef576ab9fddd9ef5d52307a4356b30e34aaaacf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
